version: '3.7'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: concept
    port:
      - "8080:8080"
    volumes:
      - "./app.js:/usr/src/app/app.js"
      - "./public:/usr/src/app/public"
      - "./views:/usr/src/app/views"
      - "./words:/usr/src/app/words"
